#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run build when source files have changed
npm run build

# Stop when dist folder has changes
modifiedDist=$(git ls-files --modified dist | wc -l)
if [ $modifiedDist != 0 ]; then
  git commit --amend --no-edit --no-verify
  echo "Auto added the dist folder with 'git commit --amend', run 'git push' now" && exit 1
fi
